### ISSUE TITLE
Add top1-seo-service.com

### ISSUE THREAD

**Issue by bassocantoris** [piwik/referrer-spam-blacklist#216]
Three visits to my low-traffic website in quick succession from different countries make me suspect that
top1-seo-service.com
creates referrer spam.

**Comment by fvdm** [comment]
This was closed in #206

**Comment by mnapoli** [comment]
:+1: thanks @fvdm

**Comment by ElWebs** [comment]
that is is one spam site
i see something like http://top1-seo-service.com/try.php?u=myurl.com 
and not only on one site it is doing this to 3 of my main websites a lot.
It is misleading if you are not tracking where your referrers are from because they spent about a minute on the site so you will think maybe its a potential buyer
