### ISSUE TITLE
непереводимая.рф

### ISSUE THREAD

**Issue by brodjustice** [piwik/referrer-spam-blacklist#22]
This one points to some odd 'portal' with search, not quite sure what they are up to.

First time we've seen one in non-latin characters. Also wondering, is it just us or is everybody being overwhelmed by referrer spam?

**Comment by mnapoli** [comment]
There is one entry with non-latin characters in the list for now: https://github.com/piwik/referrer-spam-blacklist/blob/master/spammers.txt#L107 

Where did you see this domain appear? (Piwik, Google Analytics, logs, …) Do you get a lot of traffic from them or could it be that it's a real visitor coming from there?

**Comment by brodjustice** [comment]
Glad you asked that question. This is 'standard referrer' spam, i.e. in Google Analytics, 100% bounce, high percent of the traffic all in one short period of time. The website that it re-directs to is exactly the same layout as those spammers at 'ilovevitaly.*'

However, there is also something new to us, this also seems to be 'keyword spam'.  In Google Analytics it turns up in Acquisition -> All Traffic -> Channels -> Organic Search. Here it took up over 80% of one of our clients 'organic search' yesterday. The network was 100% ertelecom.ru, locale was 100% ru, OS was 100%  iOS, city was 100% Samara, and all hits came with a 1 hour burst.

Maybe there is something I don't understand about this, but will putting these guys in this 'referrer spam' list will not stop this 'keyword spam'?

**Comment by mnapoli** [comment]
Thanks for the details, it seems we can add this one to the list.

> will putting these guys in this 'referrer spam' list will not stop this 'keyword spam'?

If you are using Google Analytics there is nothing automatic. You need to enter manually this list in the settings (and then I can't tell you if it will block the keyword spam too). On the other side we integrate the list automatically in Piwik so that users don't have to do anything (there is no such feature in Google Analytics for now). We keep the list open however so that everyone can contribute to it and use it, even outside of Piwik.

If you want more information on this: http://piwik.org/blog/2015/05/stopping-referrer-spam/
