### ISSUE TITLE
trafficmonetize.org

### ISSUE THREAD

**Issue by brodjustice** [piwik/referrer-spam-blacklist#24]
Finding the next referrer spammer is becoming a daily routine :-(

This one created about 20% of a customers traffic over 3 days, 100% bounce rate, all traffic from various Russian cities, though the domain itself is registered in Queensland Australia.

It redirects to 'traffic-paradise.org' which then leads to adzos.com.

**Comment by mnapoli** [comment]
Thanks for the report and the detailed info, I think it's good to have some background. I have added it to the list: https://github.com/piwik/referrer-spam-blacklist/commit/01fc24be532f115fa798082a4a9888904f9d33d2

FYI you can create pull requests very simply by clicking the edit button on the file: https://github.com/piwik/referrer-spam-blacklist/blob/master/spammers.txt It's all done automatically when you save your changes.

**Comment by Raydian51** [comment]
Hi,

Does someone have a link to a working guide to add these filters correctly?
I just feel it's been a couple of days and I see that more sites are
appearing in my list instead of disappearing.

Thanks!

Raynaldo Perez
raynaldo@submitexpress.com <gretchen@submitexpress.com>
818-567-3030 ext 231
Submit Express, Inc  - www.submitexpress.com

**Comment by mnapoli** [comment]
@Raydian51 see this comment: https://github.com/piwik/referrer-spam-blacklist/issues/22#issuecomment-108270152

Short answer, this list is integrated automatically in Piwik. But in Google Analytics you have to configure it yourself, I don't really use it so I can't help you much. Have a look at this blog post if it helps: https://piwik.org/blog/2015/05/stopping-referrer-spam/
