### ISSUE TITLE
How to manually update Piwik with spammer list

### ISSUE THREAD

**Issue by myfirstnameispaul** [piwik/referrer-spam-blacklist#35]
It is not clear to me how I update Piwik with the latest list.

My experience with spam is that spammers tend to redouble their efforts when encountering resistance, and I am seeing 100dollars-seo.com more than I saw any previous spam domain. I do see this domain is on the current spammers.txt maintained here, but it is not clear how I manually update Piwik, as the current instructions seem more geared to developers.

**Comment by mnapoli** [comment]
Hi! Currently the list is bundled inside Piwik and the only thing you can do is keep Piwik up to date (so it will install the latest versions of the list).

Since referrer spam is becoming a more and more important issue, we have decided to add an auto-update mechanism (with support for manual update) in the next version, see this comment: https://github.com/piwik/piwik/issues/7674#issuecomment-111369183
