### ISSUE TITLE
"Traffic exchange" sites

### ISSUE THREAD

**Issue by sndrr** [piwik/referrer-spam-blacklist#596]
Like hitleap.com or 10khits.com.

I'm not opening a PR, but I'd like to discuss this first. You can post an URL into their systems, and they will _generate_ traffic to the URL. They do access the aforementioned URL, but it is all automated.

Does this count as referral spam too?

**Comment by spmedia** [comment]
sndrr,

I would lean towards no on this issue because these are legitimate websites that have been around for years. Referral spam that we want to block is generally coming from websites that inject their domain into your analytics via sneaky methods/scripts.

I will keep issue open for now to see if any others wish to chime in on this.
